sudo: required
services:
  - docker

before_install:
  - docker build -t grelapa/docker-react -f Dockerfile.dev .

script:
  - docker run grelapa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
